[Prospect]
git-tree-sha1 = "d375585cf29f698ec29e98b694cf59c384dfbe70"
lazy = true

    [[Prospect.download]]
    sha256 = "cf16a0ed15930fe574d01c7ca8b75bb4d7b1f54a32949aa76b0dd7693d0de804"
    url = "https://raw.githubusercontent.com/ashiklom/ResearchArtifacts/prospect-versions/prospect.tar.gz"
